name: women_safety_app
description: A Flutter app designed for women's safety with permission requests, login, and alert functionality.
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.5
  http: ^1.3.0
  volume_watcher: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/police_logo.png
